# This is a basic workflow to help you get started with Actions

name: Android CI build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Tests for APK
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.2
        with: 
          java-version: 1.8
      - name: Run unit Test
        run: ./gradlew testDebugUnitTest
      - name: Build debug APK
        run: ./gradlew :app:assembleDebug --stacktrace
      - name: Check dependency updates
        run: ./gradlew dependencyUpdates
      - name: Upload dependency updates report
        uses: actions/upload-artifact@v1
        with:
          name: dependency-updates
          path: build/dependencyUpdates
      - name: Upload APK
        uses: actions/upload-artifact#v1
        with:
          name: build-output-apk
          path: app/build/outputs/apk/debug/app-debug.apk
